export const products = [
  {
    id: 1,
    category: "Pods",
    name: "Vespor Airpuds",
    price: 15.99,
    discountPrice: 14.49,
    description: "Wireless earbuds with compact design and long battery life.",
    feature: "Quad Mic, 40hr Battery, Fast Charging",
    color: "Midnight Black",
    image: "./img/pods1.webp",
  },
  {
    id: 2,
    category: "Pods",
    name: "Eclipse Earbuds",
    price: 16.99,
    discountPrice: 15.49,
    description: "Noise-cancelling earbuds in a sleek black finish.",
    feature: "OLED Display, Sleep Tracking, Step Counter",
    color: "Matte Black",
    image: "./img/pods2.webp",
  },
  {
    id: 3,
    category: "Pods",
    name: "Nova Buds",
    price: 15.49,
    discountPrice: 14.49,
    description: "Comfortable wireless earbuds with smooth pairing.",
    feature: "Bluetooth 5.3, USB-C, Overcharge Protection",
    color: "Rose Gold",
    image: "./img/pods3.webp",
  },
  {
    id: 4,
    category: "Pods",
    name: "Galaxy Pods",
    price: 18.99,
    discountPrice: 16.49,
    description: "Sporty earbuds with dual microphones for clear calls.",
    feature: "Heart Rate Monitor, GPS, Water Resistant",
    color: "Steel Grey",
    image: "./img/pods4.webp",
  },
  {
    id: 5,
    category: "Watch",
    name: "LUXE Smart Watch",
    price: 39.99,
    discountPrice: 34.49,
    description: "Smartwatch with vibrant display and fitness tracking.",
    feature: "Heart Rate Monitor, GPS, Water Resistant",
    color: "Rose Gold",
    image: "./img/w-1.webp",
  },
  {
    id: 6,
    category: "Watch",
    name: "Rugged Smart Watch",
    price: 42.99,
    discountPrice: 40.49,
    description: "Rugged smartwatch with multiple sports modes.",
    feature: "Deep Bass, Voice Assistant, Foldable Design",
    color: "Forest Green",
    image: "./img/w-2.webp",
  },
  {
    id: 7,
    category: "Watch",
    name: "LUXE Smart Watch",
    price: 37.49,
    discountPrice: 35.49,
    description: "Stylish smartwatch with metallic finish.",
    feature: "Smart AI Assistant, Sweatproof, Magnetic Case",
    color: "Coral Red",
    image: "./img/w-3.webp",
  },
  {
    id: 8,
    category: "Watch",
    name: "Rugged Smart Watch",
    price: 35.99,
    discountPrice: 34.49,
    description: "Smartwatch with health monitoring features.",
    feature: "OLED Display, Sleep Tracking, Step Counter",
    color: "Steel Grey",
    image: "./img/w-4.webp",
  },
  {
    id: 9,
    category: "Watch",
    name: "LUXE Smart Watch",
    price: 33.99,
    discountPrice: 32.49,
    description: "Minimalist smartwatch with full-screen display.",
    feature: "Deep Bass, Voice Assistant, Foldable Design",
    color: "Matte Black",
    image: "./img/w-5.webp",
  },
  {
    id: 10,
    category: "Watch",
    name: "Rugged Smart Watch",
    price: 31.99,
    discountPrice: 30.49,
    description: "Hybrid design smartwatch with leather strap.",
    feature: "Anti-slip Design, Quick Sync, Wide Compatibility",
    color: "Forest Green",
    image: "./img/w-6.webp",
  },
  {
    id: 11,
    category: "Watch",
    name: "Luxe Smart Watch",
    price: 34.49,
    discountPrice: 33.49,
    description: "Tough design watch with advanced sensors.",
    feature: "Bluetooth 5.3, USB-C, Overcharge Protection",
    color: "Glacier Blue",
    image: "./img/w-7.webp",
  },
  {
    id: 12,
    category: "Pods",
    name: "Wave Earbuds",
    price: 21.99,
    discountPrice: 20.49,
    description: "Glossy blue true wireless earbuds with rich sound.",
    feature: "Bluetooth 5.3, USB-C, Overcharge Protection",
    color: "Ocean Blue",
    image: "./img/zero-1.webp",
  },
  {
    id: 13,
    category: "Pods",
    name: "Arcade Earbuds",
    price: 22.99,
    discountPrice: 20.49,
    description: "Compact case wireless earbuds with high clarity audio.",
    feature: "Smart AI Assistant, Sweatproof, Magnetic Case",
    color: "Forest Green",
    image: "./img/zero-2.webp",
  },
  {
    id: 14,
    category: "Pods",
    name: "Quantun Earbuds",
    price: 24.49,
    discountPrice: 22.49,
    description: "Dual-tone finish earbuds with enhanced bass.",
    feature: "Smart AI Assistant, Sweatproof, Magnetic Case",
    color: "Midnight Black",
    image: "./img/zero-3.webp",
  },
  {
    id: 15,
    category: "Extras",
    name: "White Adaptor",
    price: 8.99,
    discountPrice: 7.49,
    description: "Compact USB power adapter for quick and safe charging.",
    feature: "Heart Rate Monitor, GPS, Water Resistant",
    color: "Midnight Black",
    image: "./img/adaptor.webp",
  },
  {
    id: 16,
    category: "Extras",
    name: "Black Adaptor",
    price: 10.99,
    discountPrice: 9.49,
    description: "High-speed charging adaptor with sleek black design.",
    feature: "Anti-slip Design, Quick Sync, Wide Compatibility",
    color: "Ocean Blue",
    image: "./img/adaptor-2.webp",
  },
  {
    id: 17,
    category: "Extras",
    name: "Chain Strap",
    price: 6.49,
    discountPrice: 5.49,
    description: "Durable and stylish chain strap for smartwatches.",
    feature: "Active Noise Cancellation, Touch Controls, IPX5 Water Resistant",
    color: "Midnight Black",
    image: "./img/chain-strap.webp",
  },
  {
    id: 18,
    category: "Extras",
    name: "Charging Cable",
    price: 4.99,
    discountPrice: 3.49,
    description: "Fast charging Type-A to Micro USB cable.",
    feature: "Active Noise Cancellation, Touch Controls, IPX5 Water Resistant",
    color: "Matte Black",
    image: "./img/charging-cable.webp",
  },
  {
    id: 19,
    category: "Extras",
    name: "Handsfree 1",
    price: 5.99,
    discountPrice: 4.49,
    description: "Wired handsfree with crystal-clear sound quality.",
    feature: "Multi-Device Pairing, Noise Isolation, Lightweight Build",
    color: "Pearl White",
    image: "./img/handsfree-1.webp",
  },
  {
    id: 20,
    category: "Extras",
    name: "Handsfree 2",
    price: 6.99,
    discountPrice: 5.49,
    description: "Comfortable fit with noise isolation.",
    feature: "Anti-slip Design, Quick Sync, Wide Compatibility",
    color: "Rose Gold",
    image: "./img/handsfree-2.webp",
  },
  {
    id: 21,
    category: "Extras",
    name: "Handsfree 3",
    price: 5.49,
    discountPrice: 4.49,
    description: "Classic handsfree for daily use with built-in mic.",
    feature: "Quad Mic, 40hr Battery, Fast Charging",
    color: "Forest Green",
    image: "./img/handsfree-3.webp",
  },
  {
    id: 22,
    category: "Headphone",
    name: "Headphone 2",
    price: 19.99,
    discountPrice: 18.49,
    description: "Over-ear wired headphones with deep bass.",
    feature: "Dual Pairing, Low Latency Mode, Type-C Charging",
    color: "Matte Black",
    image: "./img/headphone-2.webp",
  },
  {
    id: 23,
    category: "Headphone",
    name: "Headphone 3",
    price: 22.49,
    discountPrice: 20.49,
    description: "Stylish design and high-quality audio.",
    feature: "Dual Pairing, Low Latency Mode, Type-C Charging",
    color: "Coral Red",
    image: "./img/headphone-3.webp",
  },
  {
    id: 24,
    category: "Headphone",
    name: "Headphone 4",
    price: 24.99,
    discountPrice: 22.49,
    description: "Premium wired headphones for immersive sound.",
    feature: "Quad Mic, 40hr Battery, Fast Charging",
    color: "Champagne Silver",
    image: "./img/headphone-4.webp",
  },
  {
    id: 25,
    category: "Headphone",
    name: "Headphone 5",
    price: 18.99,
    discountPrice: 16.49,
    description: "Affordable option with clear audio and mic.",
    feature: "Smart AI Assistant, Sweatproof, Magnetic Case",
    color: "Ocean Blue",
    image: "./img/headphone-5.webp",
  },
  {
    id: 26,
    category: "Headphone",
    name: "Headphone 6",
    price: 20.99,
    discountPrice: 18.49,
    description: "Balanced sound, perfect for calls and music.",
    feature: "Smart AI Assistant, Sweatproof, Magnetic Case",
    color: "Steel Grey",
    image: "./img/headphone-6.webp",
  },
  {
    id: 27,
    category: "Extras",
    name: "Leather Strap",
    price: 7.99,
    discountPrice: 6.49,
    description: "Genuine leather strap for a classy watch look.",
    feature: "OLED Display, Sleep Tracking, Step Counter",
    color: "Rose Gold",
    image: "./img/leather-strap.webp",
  },
  {
    id: 28,
    category: "Extras",
    name: "Neck Band",
    price: 13.99,
    discountPrice: 12.49,
    description: "Bluetooth neckband with long battery life.",
    feature: "OLED Display, Sleep Tracking, Step Counter",
    color: "Matte Black",
    image: "./img/neck-band.webp",
  },
 {
  id: 29,
  category: "Extras",
  name: "OTG Adapter",
  price: 3.99,
  discountPrice: 2.49,
  color: "Jet Black",
  feature: "High-Speed Data Transfer, Compact Design, Plug & Play",
  description: "Mini USB OTG adapter for file transfer and accessories.",
  image: "./img/otg.webp",
},
{
  id: 30,
  category: "Extras",
  name: "Power Bank 1",
  price: 29.99,
  discountPrice: 24.89,
  color: "Space Grey",
  feature: "10,000mAh, Dual USB Ports, LED Indicator",
  description: "10,000mAh portable charger with dual USB ports.",
  image: "./img/powerbank-1.webp",
},
{
  id: 31,
  category: "Extras",
  name: "Power Bank 2",
  price: 34.99,
  discountPrice: 29.49,
  color: "Metallic Blue",
  feature: "Slim Design, Fast Charging, USB-C Support",
  description: "Slim power bank with fast charging support.",
  image: "./img/powerbank-2.webp",
},
{
  id: 32,
  category: "Extras",
  name: "Smart Tracker",
  price: 14.99,
  discountPrice: 11.25,
  color: "Coral Red",
  feature: "Bluetooth 5.1, Key Finder, App Control",
  description: "Bluetooth tracker to locate your essentials quickly.",
  image: "./img/smart-tracker.webp",
},
{
  id: 33,
  category: "Extras",
  name: "Speaker",
  price: 16.99,
  discountPrice: 13.49,
  color: "Midnight Black",
  feature: "Rich Bass, Bluetooth 5.0, 8hr Playtime",
  description: "Portable speaker with rich bass and Bluetooth 5.0.",
  image: "./img/speaker.webp",
},
{
  id: 34,
  category: "Extras",
  name: "Type-C Charging Cable",
  price: 5.99,
  discountPrice: 4.19,
  color: "Silver Grey",
  feature: "Durable Nylon Braid, 3A Fast Charging, 1.2m Length",
  description: "Durable and fast USB Type-C charging cable.",
  image: "./img/type-c-charging.webp",
}

];
